### ISSUE TITLE
LFQ values from DIA search produce different results when run again with same parameters

### ISSUE THREAD

**Issue by animesh** [cox-labs/CoxLab_Bug_Reporting#103]
First i must commend that finally i can reproduce Intensity values from my beloved MaxQuant, shown below are scatter (x-run1, y-run2, R^2 in blue)

![image](https://github.com/user-attachments/assets/c318c2fe-924f-4412-b38a-a9fc95f66a07)

this something i have been dying to see before, kudos to the dev-team 💯 

**Describe the bug**
LFQ values from DIA search produce different results when run again with same parameters although Intensity values are same as shown above.
![image](https://github.com/user-attachments/assets/73b9f39d-0361-4d73-a2b8-36f408d6b652)

**To Reproduce**
Steps to reproduce the behavior have been published at https://fuzzylife.substack.com/p/proteomics-data-processing-with-maxquant . The parameter is 
[mqpar.xml.txt](https://github.com/user-attachments/files/16439166/mqpar.xml.txt); run1 [parameters.txt](https://github.com/user-attachments/files/16439176/parameters.txt), run2 [parameters.txt](https://github.com/user-attachments/files/16439180/parameters.txt) where data is from https://bioshare.bioinformatics.ucdavis.edu/bioshare/view/cts8a50sb36put8/ and proteome is available in [fasta.zip](https://github.com/user-attachments/files/16439221/fasta.zip).

**Expected behavior**
LFQ values should not change given Intensity values are same? Is the algorithm for LFQ open sourced? We can probably try to recalculate using Intensity values and confirm which one is correct/debug probably?

**Screenshots**
As shown above

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 2.6.3.0

**Additional context**

**Comment by bi-MPIB** [comment]
Hi Animesh,
in our internal test of timsDIA data the two proteinGroups.txt tables have exactly the same values.
Could you please try to reproduce the LFQ error on a different computer?
Another helpful test would be doing partial processing from `Label-free preparation` and see if the LFQ values are different every time.
Best,
Wenjie

**Comment by animesh** [comment]
Partial-processing is agreeing to its full-processing 💯 
![image](https://github.com/user-attachments/assets/da6865d9-1d35-4f47-9e2a-e2043cdb33c2)

I can give it another shot to full analysis over a different computer, it will take about 3 days though. Meanwhile could you download the data at your end and check as well?

**Comment by bi-MPIB** [comment]
Maybe start the run with 2 or 3 raw data instead all of them.

**Comment by bi-MPIB** [comment]
I think starting two exactly the same run of 2 raw files would be faster than starting one run with 8 raw files.

**Comment by bi-MPIB** [comment]
I checked again the your parameter file, the difference could be that you used `LFQ min ratio count DIA` as 1 but I used the default as 3. Could you please set it to 3 and run two times partial processing to see if the data are consistent?

**Comment by animesh** [comment]
i can do that 💯  meanwhile this really won't address the original problem of having same intensity values but different LFQ. I am sharing run1-[proteinGroups.txt](https://github.com/user-attachments/files/16441825/proteinGroups.txt) and run2-[proteinGroups.txt](https://github.com/user-attachments/files/16441819/proteinGroups.txt) results, could you run the LFQ part of the algorithm and see which one is correct?

**Comment by bi-MPIB** [comment]
I ran two repeats using `26june24_hel50_100spd_OT_1ulirt_S2-B2_1_6364.d` and `26june24_hel50_100spd_OT_1ulirt_S2-A2_1_6363.d` files with exactly the same parameter as you posted. All the txt output files are exactly the same.

**Comment by animesh** [comment]
that is great to hear @bi-MPIB 👍 thanks for running through it 🙏 which results does it match with? the first run or the second from my side? also, is the MaxLFQ code open-sources?

**Comment by bi-MPIB** [comment]
[Bug_103LFQ.zip](https://github.com/user-attachments/files/16467551/Bug_103LFQ.zip)
It's not directly comparable with your data as I only used two raw data. I would still suggest you to test on other computers.

I think the MaxLFQ code is not open-souces--if it was, you would already find it online. However, the detailed explaination is available in the paper.

**Comment by animesh** [comment]
thanks for sharing @bi-MPIB , it looks relatively closer to the first run results 

![image](https://github.com/user-attachments/assets/46541858-f3d0-4311-ae1d-527d3c9936d4)

although R^2 are not so great which as you said it due to only two files but why does the intensity values are also not correlating well?

![image](https://github.com/user-attachments/assets/8d278869-90a5-4cb9-90b8-9c07536c5992)

does MBR make the difference in DIA, i didn't use it in my searches, did you?

**Comment by bi-MPIB** [comment]
I used exactly the same parameters as you provided, which you can also find in each txt folder.

As you already got inconsistent LFQ data before, which is not the case from my side, I am not sure it's a good idea to still compare with your previous data. Maybe rerun everything on a new PC and see what happens.

**Comment by animesh** [comment]
yes, i will do that 💯 but what is your comment on difference in intensity values? could you add one more file to your search and see if that changes for you as well?

**Comment by animesh** [comment]
looks like the correlation is about 0.5 in log2-space for intensity values for those two file on my computer using the same parameters

<img width="226" alt="image" src="https://github.com/user-attachments/assets/7d88d57d-e56b-4838-9225-81281b414762">


its get a little better for one and worse for another in LFQ-values

<img width="228" alt="image" src="https://github.com/user-attachments/assets/247f11bb-ddb5-4d07-babb-b1ec5da08abd">


the differences are mostly in the median region, what could be reason for that? is it protein-inference cos i do see there is about 4000 overall IDs with 3000 overlapping

<img width="186" alt="image" src="https://github.com/user-attachments/assets/6ecbda5c-5b36-4440-b1a5-518b2a195645">

uploading zipped results are here [txt.zip](https://github.com/user-attachments/files/16486567/txt.zip) for your perusal.

**Comment by bi-MPIB** [comment]
Hi animesh,

I can't follow up with what you are doing here now. In the dot plots I can't see the labels clearly and in the zip file there is only 1 txt folder.

Anyway, for the LFQ values I think it might be something wrong with your older computer. If you run the same data twice using exactly the same parameters on a different computer the results should be exactly the same. At least this is the case from my side.

Using different number of raw data will generate different intensity values, this is expected. Because the PSMs from all the raw data are going though XGBoost together, adding more raw data would affect the scoring of the other PSMs and thus affect the intensity of peptides and proteins.

Best,
Wenjie

**Comment by animesh** [comment]
Sorry for the confusion @bi-MPIB , yes it confusing. I will try to have one more go, so what i have tried is replicating your analysis of those two files on two different computers here and none of them is agreeing to your results using same parameters, please check https://github.com/user-attachments/files/16486567/txt.zip where the R^2 is about 0.5 as shown is my last post. Wondering, if you run the same analysis on a different computer, are you getting same values? 

AFAIK, my own results with 7 files are not agreeing with results on two different computers... i think the predicted library is not the same to begin with, is there a way to check if the library is same on two different computers?

**Comment by bi-MPIB** [comment]
Different computers might have different Windows system or different dotnet, which would also affect the mathmathics calculation because of rounding of decimals. But let me know if you have different output on the same computer with exactly the same paratemers.

You could find the library generated in \combined\libs\g0\, they are names `evident.txt` and `msms.txt`.

**Comment by animesh** [comment]
It worked perfectly well on the Linux cluster https://github.com/cox-labs/CoxLab_Bug_Reporting/issues/105#issuecomment-2283782020 👌
