### ISSUE TITLE
FAIMS SET UP PROBLEM

### ISSUE THREAD

**Issue by aarango1** [cox-labs/CoxLab_Bug_Reporting#109]
**Describe the bug**
My MaxQuant crashed any time I try to use FAIMS.
I find the same problem in Assembling proteins step always.

I tried different max quant versions and all of them showed the same error, one the versions just closes without showing the error, i just have to check the .txt files for error and it was the same one.

Is there any way to use FAIMS set up? 
My data was acquire using Orbitrap FAIMS.
I converted my files from RAW to MzXML and run using Standard mode and it worked but I have read that I might lose information with the conversion.

I used MaxQuant 2.6.2 and 2.4.9 beside others.

Thanks

**Comment by axolotglove** [comment]
Could you please share your mqpar.xml file and the error message?

**Comment by aarango1** [comment]
Sure! I am not sure why I did not have the mqpar file in my folder but I created one with the same parameters that I used before
[Assembling_proteins 0116.error.txt](https://github.com/user-attachments/files/16617159/Assembling_proteins.0116.error.txt)
[Assembling_proteins 0116.error.txt](https://github.com/user-attachments/files/16617165/Assembling_proteins.0116.error.txt)
[mqpar_new.txt](https://github.com/user-attachments/files/16617253/mqpar_new.txt)

Thanks

**Comment by axolotglove** [comment]
One gets this error message when running FAIMS files with a Match between runs. Unfortunately, this feature has not been implemented yet for FAIMS. Please set up a new run with a Match between runs off.
