### ISSUE TITLE
stay at "Preparing searches" step  without bug reported

### ISSUE THREAD

**Issue by stevencapeng** [cox-labs/CoxLab_Bug_Reporting#117]
I tried to run proteomic data (.raw) using maxquant 2.0.3.0, but it stuck at step "Preparing searches" without report any bugs. The mqpar file has been attached. Could anyone please help me to solve this problem? Many thanks!
[mqparlinux2.zip](https://github.com/user-attachments/files/17302646/mqparlinux2.zip)
system: centos8; .NET Core: 3.1; maxquant is installed in conda.

**Comment by WalterViegener** [comment]
Please try our most recent version and let me know if it's still stuck. Keep in mind that you net .net8 for that

**Comment by stevencapeng** [comment]
Yeah, it's been solved perfectly, thank you so much!

**Comment by xieshushu-oo** [comment]
> Yeah, it's been solved perfectly, thank you so much!

Hello, could you please tell me how you solved it? I also encountered the same problem and I'm currently stuck at the "Preparing searches" stage. I am using version 2.0.3.0 of MaxQuant.

**Comment by WalterViegener** [comment]
That is not a recent version
