### ISSUE TITLE
Error during library generation for DIA search

### ISSUE THREAD

**Issue by animesh** [cox-labs/CoxLab_Bug_Reporting#120]
**Describe the bug**
Trying to search DIA data using library generated directly from a Fasta file but it seems to fail with 
[Generate_libraries 11.error.txt](https://github.com/user-attachments/files/17449702/Generate_libraries.11.error.txt) message. Also included errors such as [Library_prediction_0 0112.error.txt](https://github.com/user-attachments/files/17449704/Library_prediction_0.0112.error.txt) 

**To Reproduce**
Steps to reproduce the behavior 
[mqpar.xml.txt](https://github.com/user-attachments/files/17449715/mqpar.xml.txt)

**Screenshots**
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/42519a46-47c6-4452-b853-a1d82d92a949">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.6.5

**Additional context**
Includes phoSTY mods

**Comment by WalterViegener** [comment]
Dear animesh, 
We do not support library prediciton for phospho data. 

Best,
Walter
