### ISSUE TITLE
Tools > MS/MS intensity prediction -- Cannot parse file

### ISSUE THREAD

**Issue by hspekt** [cox-labs/CoxLab_Bug_Reporting#133]
The MS/MS intensity prediction tool returns "Cannot parse [filepath] msms.txt" 

The return is consistent for multiple different msms.txt files I have tried, both DDA and MaxDIA searches. 

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - MaxQuant 2.6.6.0

Many thanks for any help! If you think it is a header issue, would you please provide a msms.txt that works and I can simply change the headers in my files for now.

**Comment by comaecliptic** [comment]
Dear Harrison,
It shouldn't be a header issue, an unmodified msms.txt file from DDA search should work (but not MaxDIA).
I'm attaching a file that works, just in case. Can you also provide something that is not working for me to debug?
[msms_short.zip](https://github.com/user-attachments/files/18109328/msms_short.zip)

**Comment by hspekt** [comment]
[msms.txt](https://github.com/user-attachments/files/18116301/msms.txt)

Thank you for the test file, it works! Here's one that does not for me.

**Comment by hspekt** [comment]
One difference in the files is the encoding. 

Mine is utf-8, msms_short is utf-16le

Could this matter?

**Comment by hspekt** [comment]
Seems to have been an encoding issue! Used the below snippet in R to re-encode our other msms.txt and they will now also work: 

```
ev<-read.delim(".../msms.txt", check.names = F, sep="\t")

write.table(ev,".../msms_edit.txt", 
            fileEncoding = "utf-16",
            row.names = F, sep="\t", 
            quote=F)
```

**Comment by comaecliptic** [comment]
Ah, you were faster to tackle it, good job! It's interesting that all your files had different encoding. I guess it's a system thing.
