### ISSUE TITLE
Adding Isotopic corrections for 18plex TMT is not working properly?

### ISSUE THREAD

**Issue by ChrisRampitsch** [cox-labs/CoxLab_Bug_Reporting#14]
**Describe the bug**
Adding Isotopic Label Corrections is not possible for 18plex

**To Reproduce**
In v2.2.0.0 
Go to: "Group Specific Parameters" -> "Type" = Reporter Ion MS2.
Select any TMT plex (e.g. 18plex)
Then press Edit for any label
Then for any correction factor (e.g. -2[%]) press [+] and enter values for -2x 13C and -13C-15N (e.g. select 1% and 2% respectively)
These values are not saved into the main Table upon closing the Define Isobaric Label window.

It is therefore only possible to specify a single value for each correction, not two as given by the Thermo Product Data Sheet for the TMT kit.

**Expected behavior**
1. In the "Define Isobaric Label" pop-up window, Define "Internal Label" and "Terminal Label" as "TMTpro 18plex-Lys134C" and "TMTpro 18plex-Lys135N" respectively.
2.  This populates the Isobaric Labels table (previous window) correctly, as it should, after you press OK.
3.  Entering any values for Correction Factor (in the "Define Isobaric Label" pop-up window) will also work, but NOT if you use the [+] button to enter 2 values per isotope.  In this case the Isobaric Labels table (previous window) stays blank.

**Screenshots**

![Maxquant 18plex](https://user-images.githubusercontent.com/121882184/210391585-086faf71-915c-4690-9a08-2ae870701bdf.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 21H2
 - Version e.g. 2.2.0.0

**Additional context**
I have contacted another lab <bmuseliu@uoguelph.ca> as I know they also use 18plex. They report the same issue.
Happy new Year!

<chris.rampitsch@agr.gc.ca>

**Comment by Ting-PKU** [comment]
We have encountered the same issue. We tried the newest version 2.3.1 of maxquant.

**Comment by danielaferretti1992** [comment]
Hi Chris,
please try the latest version.
We fixed this issue.
Best,
Daniela
