### ISSUE TITLE
Unable to access mailing list archive (Google Groups) without Google account

### ISSUE THREAD

**Issue by paulmenzel** [cox-labs/CoxLab_Bug_Reporting#25]
The [community page](https://maxquant.org/community/) says:

> If you have questions you can't find the answer to in the documentation, try asking in the Google group with the topic closest to your problem:

Unfortunately, the archive seems to be non-public. Accessing https://groups.google.com/g/maxquant-list?pli=1 I get:

> Sie sind nicht berechtigt, auf diese Inhalte zuzugreifen

I do not want to use a Google account. Is it possible to access the archive?

**Comment by danielaferretti1992** [comment]
you can use only google account
