### ISSUE TITLE
Cannot save session when using PerseusR

### ISSUE THREAD

**Issue by cbagwe** [cox-labs/CoxLab_Bug_Reporting#37]
**Describe the bug**

Using PerseusR in Perseus and R to apply Limma correction in DE analysis (which works great and I have a nice adj p value column!) I can not save the session in an sps file.

![1](https://github.com/cox-labs/CoxLab_Bug_Reporting/assets/130548832/1b1f59e3-cb90-4598-8255-8e54c3a260a6)
![2](https://github.com/cox-labs/CoxLab_Bug_Reporting/assets/130548832/1da6058c-1360-4254-a141-0f2e78280bf7)

 - Windows10

**Comment by danielaferretti1992** [comment]
Hi @cbagwe we are aware of this issue.
Sorry for the delay in fixing it
If you don´t mind I will close this issue because we have another issue post opened for the same problem.
Please follow this one for updates:
https://github.com/cox-labs/CoxLab_Bug_Reporting/issues/7

Best,
Daniela
