### ISSUE TITLE
MaxQuantGui not working on linux "Could not load file or assembly mscorlib"

### ISSUE THREAD

**Issue by rsdmse** [cox-labs/CoxLab_Bug_Reporting#39]
**Describe the bug**
`MaxQuantGui.exe` throws an error:
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

**To Reproduce**
1. We installed dotnet-sdk 3.1.426 (verified with `dotnet --list-sdks`) and MaxQuant 2.4.2.0
2. As an additional setup, we had to link certain files in dotnet to MaxQuant's `bin` directory: `ln -s /path/to/dotnet/shared/Microsoft.NETCore.App/3.1.32/* /path/to/maxquant/bin`. Otherwise it will complain about not being able to find those files.
3. Run `dotnet /path/to/MaxQuantGui.exe`

**Expected behavior**
The GUI is expected to work.

**Desktop (please complete the following information):**
 - OS: CentOS
 - Version: 7.9.2009

**Comment by fedeserral** [comment]
same issue

**Comment by WalterViegener** [comment]
Dear all, 
Unfortunately we do not support GUI for linux. Please use the commandline version (MaxQuantCmd.dll) according to https://cox-labs.github.io/coxdocs/Download_Installation.html#maxquant-on-linux
