### ISSUE TITLE
[PerseusR] PlugIn only returns "Error Output"

### ISSUE THREAD

**Issue by FlorianProdinger** [cox-labs/CoxLab_Bug_Reporting#43]
Thank you for the hard work you are putting into Perseus and Maxquant. We appreciate the software, however I am struggling with using the PerseusR interloper that we would really like to use in  our lab in the future.

**Bug descripiton**
I would like to use PerseusR, however running custom scripts always reports "Output Error" (screenshot) without generating anything in Perseus. In the "pipeline viewer" a green box saying "External" quickly appears before the error message, the green box disappears with the error box when "OK" is clicked.

It seems the script is not parsed in Perseus since even faulty scripts will produce the same error as files that only contain commented lines or supposedly functional scripts (i.e., example script from [Github](https://github.com/cox-labs/PerseusR)). The error also appears very quickly so that I think R was not actually launched (It's a slow language after all...).

Perseus itself and PerseusR were installed successfully and correctly, I believe. I followed [this tutorial ](https://www.youtube.com/watch?v=F_mPw9f9gJY)) and all the prompts from R during the installation of additional packages as well as PerseusR were identical. As test I tried using "Clustering" > "Umap" on a random matrix and it works fine. I receive an output and no error.
Only custom scripts seem to be not accepted.

**Screenshots and other data**
I added the "parameters.xml" as a zip file (upload restrictions) [parameters.zip](https://github.com/cox-labs/CoxLab_Bug_Reporting/files/12788116/parameters.zip) that can be generated when clicking the "Download Parameter for preview" button in the "External" > "Matrix => R" menu. This xml file is always the same, independent on the input.

The error I receive regardless of input script is shown here (it is not very explanatory):
![image](https://github.com/cox-labs/CoxLab_Bug_Reporting/assets/28749933/976496cb-2dd6-495d-bf3b-e45673a4533f)

**System:**
 - OS: Windows 10 enterprise
 - R's sessionInfo output:
   - R version 4.3.1 (2023-06-16 ucrt)
   - Platform: x86_64-w64-mingw32/x64 (64-bit)
   - Running under: Windows 10 x64 (build 19044)
 - Perseus 2.0.11 

Thank you for reading, I welcome all comments! If I failed to add some crucial information, please let me know.
Thank you again,
Florian

**Comment by FlorianProdinger** [comment]
I want to add to my bug report.
I also tried uploading data using R with the "R" button on the very upper left of the Perseus GUI.
I use PerseusR to preprae the data like so:

```{r}
library(PerseusR)
tab_ <- PerseusR::read.perseus(path_random_table) # this table was made in Perseus and exported.
outMdata <- matrixData(main=  main( tab_ )  )
main( outMdata ) <- main( outMdata ) +100
if( PerseusR::MatrixDataCheck( outMdata) ){ # this is 'true'
  write.perseus(outMdata, outFile)
}
```

But I receive the same error as in my original report: "Output Error".

even if I just use a script with this command:

```{r}
stop("This is an error message")
```

nothing changes. Still the same error. This happens in both Perseus 2.0.11 as well as Perseus 1.6.10.

I tried to understand the interloper better and found two commands that I think may be able to cause problems:

1. In the [github for the interloper](https://github.com/cox-labs/PluginInterop/blob/master/PluginInterop/R/MatrixUpload.cs) The interloper actually checks a variable called "ReqiredPythonPackages" for a PerseusR installation. If it actually checks Python packages and then aborts the quick output of errors would make sense.

2. There is a "CodeFilter" that checks the file extention of your R scripts. For Matrix upload it is  
```
protected override string CodeFilter => "R script, *.r | *.r";
```

  and for Matrix Processing or Analysis the CodeFilter is as such:

```
protected override string CodeFilter => "R script, *.R | *.R";
```

  I tried renaming my R scripts to end in .r and .R but neither worked. So, I do not know if case sensitivity is an issue here.

Thank you for reading.
Any help is welcome!

**Comment by bioinformatic-guy** [comment]
I am facing same issue, tried from my end to solve this issue but failed. Can anyone help, what's the exact reason behind this issue? 
Thanks in advance.

**Comment by WalterViegener** [comment]
Dear all,
Could you please let me know if the error persists with the current version (v2.1.1.0)?

**Comment by bioinformatic-guy** [comment]
Sorry, I forgot to update. I updated the Perseus and R version to 4.4, and it solved the problem. 

Thanks.
