### ISSUE TITLE
Recent installation on Windows 10 or 11 crashes when running crosslink analysis.

### ISSUE THREAD

**Issue by rmhajjh** [cox-labs/CoxLab_Bug_Reporting#51]
**Describe the bug**
MQ 2.4.9.0 crashes when writing tables only when crosslink analysis is ticked. This has occurred for different RAW and fasta files, including the Beveridge et al (2020) synthetic peptide data test run as described in Yilmaz et al (2022). NET Framework 4.8.09037 and .NET Core 3.1.32 installed. Error reported below under Screenshots.

**To Reproduce**
1. Set up MQ (as Administrator) to analyse XLpeplib_Beveridge_QEx-HFX_DSS_R1.raw against Cas9_plus10.fasta with settings as described for DSS crosslinker in Yilmaz (2022).
2. 4 threads run on 8-core Workstation or 4-core PC.
3. MQ crashes when writing tables, error recorded in proc/Writing_tables 1326.error.txt (see Screenshots)

**Expected behavior**
Completion of the analysis without crashing (MQ window closes) and with production of crosslink identification files.

**Screenshots**
Screen shot of Writing_tables 1326.error.txt
![image](https://github.com/cox-labs/CoxLab_Bug_Reporting/assets/148873719/b265a2cd-b507-436e-b376-0bc2ac21df73)

**Desktop:**
 - OS: Windows 10 Pro; Windows 11 Home (both x64)
 - Version: 22H2; 22H2

**Additional context**
None

**Comment by WalterViegener** [comment]
Thanks for the feedback. The bug is fixed with the latest release

**Comment by WalterViegener** [comment]
Bug fixed with latest release

**Comment by rmhajjh** [comment]
Many thanks
