### ISSUE TITLE
Help button in Perseus not working

### ISSUE THREAD

**Issue by ThoPatsch** [cox-labs/CoxLab_Bug_Reporting#59]
I am using Perseus Version 2.0.11
If I press the help button to get help I only receive an error message

**Comment by WalterViegener** [comment]
Dear ThoPatsch, 
We have moved the documentation to https://cox-labs.github.io/coxdocs/perseus_activities.html
Until we have updated every link in Perseus, please try to find help there. In which function did you need help?

Best, 
Walter
