### ISSUE TITLE
Failed to read the session with perseus 2.0.11.0

### ISSUE THREAD

**Issue by misha-rud** [cox-labs/CoxLab_Bug_Reporting#60]
**Describe the bug**
Cannot open .sps files created with Perseus version 2.1.4.0, after installing the new version (2.0.11.0). Is there a way to download the old (2.1.4.0) version somewhere?

**Expected behavior**
I was expected it to be able to open older version files. Also not sure why new version has a number smaller than the previous one

![Untitled-12](https://github.com/cox-labs/CoxLab_Bug_Reporting/assets/123023780/ab67bf9b-9acc-4b48-a84a-d16309ca32e7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [to create the files: 2.1.4.0; to read: 2.0.11.0 (currently available on the website)]

**Additional context**

**Comment by misha-rud** [comment]
Update: was able to open my .sps files with 2.0.5.0 version: mb there is a coding mistake in version naming (possibly it was 2.0.4.0 instead of 2.1.4.0). Anyway, the problem seems to be solved now

**Comment by Meztlimg** [comment]
I have the same problem, can you give more detail on what you did to solve the problem?
Thanks!
