### ISSUE TITLE
MaxQuant 2.5.0.0 save changes to protease configuration does not work

### ISSUE THREAD

**Issue by kim-lorenz** [cox-labs/CoxLab_Bug_Reporting#66]
Today I installed the new version of MaxQuant (2.5.0.0) and I wanted to add a new protease in the configuration mode, the same way I already did it in an earlier MaxQuant version. When I entered the name and the cleavage sites, I pressed "Save changes". Afterward, my changes were deleted and I only had an entry which was named "New protease" which did not have any of my settings. I tried this several times and also closed the program and opened it again, but it still does not work.

1. Go to 'configuration'
2. Click on 'Proteases'
3. Click on 'Add'
4. Enter the name, the description, and the specificity of a new protease
5. Click on 'Save changes'
6. Click again on your new protease in the table to see the configuration
--> You will see, that the name of the protease is still "new protease" (even if changes were made and saved) and the configuration setting was not saved. 

Expected behavior:
The changes of the newly added proteases are visible in the proteases table after clicking on "Save changes" 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2

**Comment by pelipelipeli** [comment]
![protease_new](https://github.com/cox-labs/CoxLab_Bug_Reporting/assets/75263393/9d115d58-a768-44f8-8336-bf0e6d54f496)
First, you must select 'Modify table' before selecting 'Save changes'.

**Comment by kim-lorenz** [comment]
Thank you very much, I didn't know that! It's working now.
