### ISSUE TITLE
MaxLynx cross-links quantification needed

### ISSUE THREAD

**Issue by Christian-Trahan** [cox-labs/CoxLab_Bug_Reporting#67]
Dear MQ team, it would be extremely useful to be able to have intensities reported in the crosslinkMsms.txt output for cross-linking quantification. Is it something that users could expect to be done relatively quickly?

**Comment by WalterViegener** [comment]
Dear Mr. Trahan,
We are in the process of finalizing new output tables for crosslinking, which will include intensities. We expect 
 more robust results with the support of  crosslinking DIA, which is currently underway.

Best regards,
Walter
