### ISSUE TITLE
Crosslink Search of TimsTOF DDA data error

### ISSUE THREAD

**Issue by julian-langer** [cox-labs/CoxLab_Bug_Reporting#68]
**Describe the bug**
We acquired DDA-PASEF data from a purified protein sample crosslinked with DSS and digested with Trypsin. We first ran a regular, non-XL-MS MQ search which worked fine (expected proteins detected with reasonable sequence coverage, only a few other proteins and contaminants present).
We then ran a XL-MS search with standard parameters against a minimal database with <10 entries. MQ did not complete the XL search and stopped at the "MS/MS_crosslink_search" step with an error (screenshot below). We tested our database with a regular search (without crosslinks) and it worked fine.
The same happened with previous versions of MQ. Notably, Orbitrap data is being processed without any issues. Also, converting the files to mzml and processing them in MetaMorpheus works fine.
So - is this a user problem (i.e. did we use wrong parameter sets?) or is there a systematic issue with XL-MS timsTOF data at present?

Many thanks for your help!

**To Reproduce**
1. load XL-MS timstof data
2. use standard parameters (DSS, trypsin, small database)
3. run MQ 2.5
4. works fine until MS/MS_crosslink_search" step, then stops 

**Expected behavior**
see above

**Screenshots**
<img width="1499" alt="MQ_screenshot_error" src="https://github.com/cox-labs/CoxLab_Bug_Reporting/assets/164176666/8926ef6f-e9f0-4da2-8777-3d059dd92f44">

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - MaxQuant Version 2.5.0.0

**Additional context**
[Reading_crosslink_search_engine_results 0128.error.txt](https://github.com/cox-labs/CoxLab_Bug_Reporting/files/14666354/Reading_crosslink_search_engine_results.0128.error.txt)
[MSMS_crosslink_search 0128.error.txt](https://github.com/cox-labs/CoxLab_Bug_Reporting/files/14666368/MSMS_crosslink_search.0128.error.txt)

**Comment by WalterViegener** [comment]
Dear Mr. Langer, 
It would be very helpful if you could upload your raw data and mqpar file to this link: 
https://datashare.biochem.mpg.de/s/C1sQ9aFUqb30cX8

Only I can see the uploaded data. The link will be disabled once I have everything. 

Best regards, 
Walter Viegener

**Comment by julian-langer** [comment]
many thanks for looking into this, i've started the upload.

**Comment by WalterViegener** [comment]
Thank you for you data. Please upload again the .d folders as zip files

**Comment by julian-langer** [comment]
upload completed.

**Comment by WalterViegener** [comment]
The bug is fixed with the latest release. I saw some things I would recommend to change in the settings. Are you Julian Langer from the biophysics institute ? If so I will just send you my mqpar settings via email. 

Best,
Walter

**Comment by julian-langer** [comment]
Dear Walter,perfect, thank you very much. Yes, i’m julian langer from the mpi of biophysics. The mqpar file would be very much appreciated.Best,JulianAm 28.03.2024 um 11:15 schrieb WalterViegener ***@***.***>:﻿
The bug is fixed with the latest release. I saw some things I would recommend to change in the settings. Are you Julian Langer from the biophysics institute ? If so I will just send you my mqpar settings via email.
Best,
Walter
