### ISSUE TITLE
Perseus session save error after using R plugin

### ISSUE THREAD

**Issue by shimin-chen** [cox-labs/CoxLab_Bug_Reporting#7]
**Describe the bug**
A session save error (failed to write session") appears after data processing using R plugin (such as quantile normalization)

This bug has also been reported by others in YouTrack and in the Google group.

**To Reproduce**
Steps to reproduce the behavior, I reduced the steps to the minimum to reproduce the error:
1. Open Perseus 2.0.7.0
2. Click on 'Create a random matrix', a matrix is generated
3. Click on Normalization, then select "Quantile normalization", another matrix is generated, which indicated that the R script ran and generated results without issues.
A screenshot of the steps
![steps](https://user-images.githubusercontent.com/44071281/189162526-207211a0-d659-4174-a9fd-3935a9953e05.png)
5. Click on "File-Save", see error
![write sessionerror](https://user-images.githubusercontent.com/44071281/189162641-f64b94d5-e342-47f5-b711-c0cc78bfe99f.png)
6. After clicking "Ok", a second window showed up
![Second error](https://user-images.githubusercontent.com/44071281/189162855-c5b28b36-c42b-42d4-8237-0dfbc45dd11e.png)

**Expected behavior**
I expect the session to be saved and reloaded just like ones where R plugins are not involved.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, version 20H2
 - Perseus Version 2.0.7.0 (same error was seen in previous versions as well, as reported by others)
 - R Version: 4.2.1

**Additional context**
All necessary R packages, such as PerseusR, BioBase, devtools have been installed properly.

**Comment by hcadre** [comment]
I observed the identical error with my install of Perseus version 2.0.7.0, unfortunately within the context of a more complex analysis (R plugin Quantile Normalization also applied before attempts to save session failed):
![image](https://user-images.githubusercontent.com/16349515/192791882-089f10c4-ea48-4457-ba56-a9e60845bd53.png)
![image](https://user-images.githubusercontent.com/16349515/192791966-71b8d8c8-2015-4ef0-8f75-cc8a9b6ca4d3.png)
![image](https://user-images.githubusercontent.com/16349515/192792028-f4426ab9-34fd-4405-a03e-2c43ebb9b268.png)

**Comment by prsu12395** [comment]
I have the same error. I could save the session until I added the anlaysis node with R (Run DE analysis).

Windows 10
Perseus 2.0.7.0
R 4.2.1
PerseusR 0.3.4

**Comment by fionamassspec** [comment]
Hi all,
I have encountered the same problem which prevented me from saving the session. Not sure if you have fixed that or anything I can provide to investigate. @hcadre @enonimos @danielaferretti1992 @shimin-chen @prsu12395 

Thanks.

**Comment by fionamassspec** [comment]
I didn't solve the problem. But it's ok to use perseus 1.6.15.0 for the same processing and could be saved successfully.

**Comment by martinowsky** [comment]
Great, good to know. I will use the 1.6.15.0 version then. Thanks!
Best,
Miguel

**Comment by hcadre** [comment]
No progress on this issue in the most recent version 2.0.9.0: inclusion of any analysis node with R (Quantile normalization, Remove batch effects, DE analysis, UMap....) blocks successful saving of the session. Same error messages displayed as described previously. This bug traces back to version 2.0.3.1 and probably beyond. So 1.6.15.0 still remains the latest version that runs without glitches in this respect. 
Best, 
Hannes

**Comment by enonimos** [comment]
To continue this thread, I can confirm the issues above with R scripting are still present for me in the most recent Perseus 2.0.10.0.  If anyone reading this thread is able to save sessions that include R processing in software versions >= 2.0.3.1, it would be interesting to know your system configuration.

**Comment by Amon789** [comment]
Same issue with Perseus 2.0.10.0 is still present, Any solutions?
 It is annoying that the solution might be simple like just simple code modification but seems like nobody cares.

**Comment by shimin-chen** [comment]
Hi all,

I had a chance to speak with one of the developers about this issue. Basically, they are aware of this problem, but due to limited resources (time, personnel, etc.), this issue is probably not going to be fixed anytime soon. 

For now, I can think of two workarounds for those who are trying to use R analysis nodes (limma, quantile normalization, DE analysis, etc.) in Perseus. 

- Option 1: use Perseus 1.6.15.0 as indicated by several people here. 
- Option 2: after using the R analysis nodes, export the result table to a CSV/TXT file, then re-import the file into Perseus. Delete R analysis nodes from your workflow (after taking a screenshot or record the parameters used in the function). Finally, save the session. The saved session should not contain any R analysis nodes.

Hope this helps.

**Comment by danielaferretti1992** [comment]
Thank you @shimin-chen for replying it.
Yes, we are aware of this issue.
Sorry for the delay in fixing it

Best,
Daniela

**Comment by Amon789** [comment]
Thank you very much for the help and quick response. I really appreciate the effort for this magnificent work which we rely on in different data manipulation and analysis. 

And sorry for the inconvenience. 
BR

**Comment by VetSciMS** [comment]
Hi Everyone, does anyone know if version 1.6.1.3 works with R?
Thanks!

**Comment by vcoyne1** [comment]
I am having the same issue with Perseus 2.0.11. How come this issue has still not been rectified?

**Comment by WalterViegener** [comment]
Dear all, 
We made a major release in July where we fixed the PluginInterop. All standard R and Python functions should be working now.  Did this solve all your issues?

All the best, 
Walter
