### ISSUE TITLE
Perseus2.0.11.0_Error when saving session after data imputation with imputeLCMD

### ISSUE THREAD

**Issue by FredTel** [cox-labs/CoxLab_Bug_Reporting#76]
**Describe the bug**
Error when saving a session. This error comes only if data imputation using the imputeLCMD plugin has been performed.

**To Reproduce**
1. load data containing NaN
2. impute data using "imputeLCMD". Choose QRLIC with default settings
3. save session

**Expected behavior**
I expected to save the session without error.

**Screenshots**
![image](https://github.com/cox-labs/CoxLab_Bug_Reporting/assets/81357485/992b8737-c3df-4b8a-9ac1-41c083fd024e)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version: 2.0.11.0

**Additional context**
Actually: a .sps file is written with the intended name. But when trying to open the session, the error "Failed to read session" pops up.

**Comment by CarloDeNart** [comment]
Such issue has been solved in the next Perseus release, we will publish the latest version soon
