### ISSUE TITLE
backslash in file paths not recognized

### ISSUE THREAD

**Issue by christophgil** [cox-labs/CoxLab_Bug_Reporting#89]
**Describe the bug**

Our absolute file paths are consistent over machines and the mqpar.xml made on Windows should work without any changes 
on other Machines uncluding Linux.

Unfortunately, MQ on Linux does not understand UNC paths in mqpar.xml with backslash.
Consequently, the mqpar.xml  generated from the GUI in Windows cannot be used directly. It needs to be edited to convert backslash to fwd slash. 

**To Reproduce**

Create an mqpar.xml with UNCs using the Windows GUI. 
UNCs are remote paths starting with double backslash.
Set mount binds or symlinks on the Linux machine such that the UNC file paths correspond to the same Volume.
Use this mqpar.xml in Linux and observe the error.

Try this mqpar.xml on Linux before and after posixification of DOS file-path-component-separators.

It will work on Linux only when the file-path-component-separators are turned into slash.

**Expected behavior**

Linux should interpret  the Windows UNCs as absolute file paths.
Leading double slash does not matter in Linux.
By this, the mqpar.xml should be portable across machines.

If you really need the distinction of fwd and backslash for UNIX and Windows, then I suggest that the GUI generates
two different mqpar.xml, one for DOS, the other for Linux. But it would be nicer to have one format which is valid for 
all OS. Many other software such as R based software use legacy file-path-component-seperators and tolerate the DOS backslash. 
I think this is easier for users to understand.

**Environment
Ubuntu 20
We can currently not run the current MQ version - respective bug-report submitted.  
Our observations are based on  v2.3.1.0.

Many thanks
Christoph

**Comment by yeroslaviz** [comment]
please take a look here - [edit mqpar.xml file](https://cox-labs.github.io/coxdocs/Download_Installation.html#edit-mqpar.xml-file).

You'll need use this command to adapt to the current folders and paths of your machine

```
dotnet MaxQuant/bin/MaxQuantCmd.dll WIN_mqpar.xml --changeFolder NEW_LINUX_mqpar.xml  library_files/ raw_dataFiles/
``
