### ISSUE TITLE
MaxQuant V2.1.4.0 crashes analyzing TMT-PRO

### ISSUE THREAD

**Issue by fgarciacnio** [cox-labs/CoxLab_Bug_Reporting#9]
Dear Maxquan Team
I tried to analyze an O480 raw file of a TMT18plex-labeled sample. Maxquant V2.1.4.0 crashed at MSMS_preparation . The message 
displayed is the following "

File 1/1_Illegal isobaric labels._   at MaxQuantLibS.Domains.Peptides.Basic.GroupParams.GetIsobaricLabels(Double[]& allMasses, String[]& allSpecificities, Modification[][]& representativeMods, Double[,]& correction, Modification[] isoLabels, Dictionary`2"
Thank you very much for your help

Fernando 

**To Reproduce**
1. MaxQuant.exe Load raw file
2. Click on 'Group specific Parameters.' Type -> Reporter ion MS2 -> 18 plex.
3. Select Mouse Uniprot database
4. Star Run MaxQuant
**Screenshots**
![image](https://user-images.githubusercontent.com/90319981/194516881-f2c70cc3-31ea-4b4c-bebd-82923d851d98.png)

![image](https://user-images.githubusercontent.com/90319981/194516957-415c235c-b333-45b4-ba06-2d49da9844cf.png)

**Desktop (please complete the following information):**
 - OS: WINDOWS10

**Additional context**
[#runningTimes.txt](https://github.com/cox-labs/CoxLab_Bug_Reporting/files/9732333/runningTimes.txt)

[MSMS_preparation 11.comment.txt](https://github.com/cox-labs/CoxLab_Bug_Reporting/files/9732335/MSMS_preparation.11.comment.txt)
[MSMS_preparation 11.error.txt](https://github.com/cox-labs/CoxLab_Bug_Reporting/files/9732336/MSMS_preparation.11.error.txt)
[mqpar.zip](https://github.com/cox-labs/CoxLab_Bug_Reporting/files/9732341/mqpar.zip)

**Comment by danielaferretti1992** [comment]
hello, we apologize for the error. 
we didn´t announce it in the "MaxQuant CHANGELOG" TMT18plex because we were working on it.
it is fixed and we will soon release a new MQ release.
Thank you

**Comment by fgarciacnio** [comment]
Thanks a lot Daniela.
I have just changed the 18plex table and it works fine. The new TAGS were wrongly defined (same name for N-term and Lys label)
Best regards
