### ISSUE TITLE
maxquant global parameters/folder location: missing option to choose a location for the combined folder 

### ISSUE THREAD

**Issue by Manuela-MQ** [cox-labs/CoxLab_Bug_Reporting#95]
**Describe the bug**
i have installed the latest version of maxquant (2.6.2.0) and the new .net version (8.0.301). under global parameters i would like to choose a location for the results (combined folder). but i only get the option to select a folder for andromeda index files. has this option been removed (it is still available in version 2.4)? is there another option to reuse the same rawfiles with different parameters without overwriting old results?

**To Reproduce**
1. Go to global parameters
2. Click on folder location'
4. See error: no option to select a location for combined folder

**Expected behavior**
I expected in addition to the option to select a location for andromeda index files an option to select a location for the result files (combined folder)

**Screenshots**
![grafik](https://github.com/user-attachments/assets/33d30c9b-dff6-4940-ba1c-d6803b6c51e1)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 22H2

**Additional context**

**Comment by comaecliptic** [comment]
No, there is no option to specify the combined folder location, it will always be generated in the same folder with the raw data. But you can rename the old combined folder from the previous run (for example, adding the parameters used in that run) and do another run with different parameters in the same place.
