### ISSUE TITLE
MaxQuant - TIMS-MaxDIA - stopped at Finish protein assembly

### ISSUE THREAD

**Issue by NathanielakaJuan** [cox-labs/CoxLab_Bug_Reporting#96]
I am running a version 2.6.2 of MQ and while I am trying to run a DIA analysis it gets stuck at the same process: Finish protein assembly. 

This process has been running for 40+h for single sample while I am using a computer with 128 threads. I tried different db - predicted or generate on MQ by myself from DDA experiments (evidence + msms). 

I have tried different versions of MQ, it was 2.5.0 at first and now I am using 2.6.2. I was running different DIA raw data from TIMS TOF Pro2. I could analyse these samples on other software like Peaks or Spectronaut but it can not go through in MQ. 

I have been trying different options and never make it through. I also saw that someone had the same problem in 2021 with DIA data because it was reported somewhere. 

There is no bug log or whatever as it just pass through all of the processes and gets stuck on Finish_protein_assembly (1/1) and the longest I waited for 120+ hours for a single DIA file...

**Comment by WalterViegener** [comment]
Dear NathanielakaJuan,
We optimized that step for large datasets and it will be part of the upcoming release. Would you mind  sharing your data (mqpar + raw file) with us? her is a link for that (Only I can see the uploaded data): https://datashare.biochem.mpg.de/s/pKx0CQKxdyuZXxM

**Comment by NathanielakaJuan** [comment]
Uploaded. Can you tell me when approximately the new (working) version will be available ? We would like to publish our data asap and just waiting for this final analysis with MQ...

**Comment by WalterViegener** [comment]
Thank you for your data ! Could you please re upload the .d folder as a zip file? and separately the mqpar file?

**Comment by NathanielakaJuan** [comment]
Done. Can you let me know approximately when the update will be available.

**Comment by NathanielakaJuan** [comment]
Does version 2.6.3 change anything in terms of TIMS-MaxDIA analysis ?

**Comment by WalterViegener** [comment]
I am currently testing it. We decided to already make the release. Please also test it yourself

**Comment by WalterViegener** [comment]
I was able to run your test data. Was your run also successful?

**Comment by NathanielakaJuan** [comment]
First of all, I appreciated your help a lot Walter.

Second of all, I am sorry that I have not replied for a while but I was away for some time. 

Third of all, it is still very important for me to make it work. I have tried with new version and I got other problem... Check below. I will try to run once again but I would appreciate if you could provide your mqpar coz maybe I am doing smth wrong. I have never used MQ for DIA before, however  I have been using MQ for 10 years... 


![image](https://github.com/user-attachments/assets/b746640b-4e1d-4189-add4-188b592dc0a8)

**Comment by NathanielakaJuan** [comment]
2nd run worked fine. I will try with all data now, not a single DIA.

Is it possible to run library based search in MQ from other software ?

**Comment by WalterViegener** [comment]
Thats good to hear! Second question answered in the issue 2nd reported by you.
