### ISSUE TITLE
MaxQuant 2.6.3.0 GUI does not work on Linux

### ISSUE THREAD

**Issue by davidhoover** [cox-labs/CoxLab_Bug_Reporting#98]
After installing the correct dotnet (8.0.302) using mamba, I can get the command-line for MaxQuant to work:

`dotnet MaxQuant_v2.6.3.0/bin/MaxQuantCmd.dll`

However, the GUI does not start:

```
$ dotnet MaxQuant_v2.6.3.0/bin/MaxQuantGui.dll
You must install or update .NET to run this application.

App: /usr/local/apps/maxquant/2.6.3.0/MaxQuant_v2.6.3.0/bin/MaxQuantGui.dll
Architecture: x64
Framework: 'Microsoft.WindowsDesktop.App', version '8.0.0' (x64)
.NET location: /usr/local/apps/maxquant/2.6.3.0/mamba/envs/try1/lib/dotnet/

No frameworks were found.

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=8.0.0&arch=x64&rid=linux-x64&os=rocky.8
```

Is this correct?  Should the GUI launch with dotnet?  Do we need something else (e.g. mono)?

**Comment by WalterViegener** [comment]
Dear davidhoover,
We currently only support GUI on Windows. `dotnet MaxQuant_v2.6.3.0/bin/MaxQuantCmd.dll` will start the CommandLine run of MaxQuant. It will do the same as the MaxQuant GUI but you have to set the parameters in either Windows or in the commandline. 

A tutorial for that is for example here: https://cox-labs.github.io/coxdocs/Download_Installation.html
