### ISSUE TITLE
Newer MQ version missing important columns

### ISSUE THREAD

**Issue by kwebber3** [cox-labs/CoxLab_Bug_Reporting#99]
**Describe the bug**
MQ doesn't have a Gene names column in proteinGroups.txt anymore

**Expected behavior**
I expected to get this column based on your documentation and older versions of the code

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.6.3.0

**Comment by kwebber3** [comment]
Update: it seems this only happens when we set a reference channel. Everything else is the same

**Comment by pelipelipeli** [comment]
You need to change in MaxQuant the Identifier rule(first screenshot) of your fasta file to have a result like the one showed in the second screenshot below. You can see the result (like the one i am showing in the second screenshot) if you select your fasta file and then press 'Test'.  The identifier rule that would work for your fasta files is:
`>[^|]*\|(.*?)\|`

![identifier_rule_1](https://github.com/user-attachments/assets/bea90432-3b62-4c44-a587-c2631c6ad592)
![identifier_rule_2](https://github.com/user-attachments/assets/9350cfdc-e4fd-4b30-b227-ae6fb65a91a1)
